### ISSUE TITLE
Segmentation fault with version 0.0.6

### ISSUE THREAD

**Issue by juanfcocontreras** [ddvk/remarkable2-framebuffer#68] opened 2021-08-13 14:50 UTC
I just upgraded my Remarkable to version 2.9.0.210 and remarkable2-framebuffer to version 0.0.6 which is supposed to be compatible, but I get:

```
308 Segmentation fault
```

However, with the previous version emarkable2-framebuffer 0.0.5 I have no problems with version 2.9.0.210 of my Remarkable.

**Comment by matteodelabre** [comment] 2021-08-13 14:58
Hi! Thanks for the report. I’m trying to reproduce your issue, but I’m going to need more details:

* Did you build remarkable2-framebuffer manually or did you install it from Toltec?
* What exact command did you run to get the segfault?

Also, I’m surprised you’re able to use 0.0.5 on OS 2.9.0.210, since it’s not working for me.

**Comment by juanfcocontreras** [comment] 2021-08-13 15:03
Thank you for your interest.

>     * Did you build remarkable2-framebuffer manually or did you install it from Toltec?

I downloaded it directly from the releases of this repository.

>     * What exact command did you run to get the segfault?

I'm using remarkable2-framebuffer to get koreader working using the following repository:

```
https://github.com/ddvk/remarkable-autoinstall/tree/master/rm2
```

Launching the script `~/scripts/ko.sh` I got the exception.

**Comment by Eeems** [comment] 2021-08-13 15:07
Looks like remarkable-autoinstall was never updated to use xochitl as the server and is still using remarkable-shutdown:

https://github.com/ddvk/remarkable-autoinstall/blob/master/rm2/scripts/ko.sh#L11

**Comment by matteodelabre** [comment] 2021-08-13 15:09
Also, the auto_rm2.sh script is fetching rm2fb release 0.0.2, so I’m assuming you have modified it to make it work?

**Comment by juanfcocontreras** [comment] 2021-08-13 15:10
> Also, the auto_rm2.sh script is fetching rm2fb release 0.0.2, so I’m assuming you have modified it to make it work?

Yes, that's just what I was going to comment on. I'm manually updating every version, and this is the first time I'm having problems.

**Comment by matteodelabre** [comment] 2021-08-13 15:13
Just tested Toltec’s KOReader package with rm2fb 0.0.6 and there’s no segfault, so this seems to come from the autoinstall script.

**Comment by juanfcocontreras** [comment] 2021-08-13 15:14
> Looks like remarkable-autoinstall was never updated to use xochitl as the server and is still using remarkable-shutdown:
> 
> https://github.com/ddvk/remarkable-autoinstall/blob/master/rm2/scripts/ko.sh#L11
> 
> Edit: It also looks like @juanfcocontreras also opened an issue about this: [ddvk/remarkable-autoinstall#17](https://github.com/ddvk/remarkable-autoinstall/issues/17)

Exactly, the complete error trace is:

```
./scripts/ko.sh: line 12:   435 Segmentation fault      LD_PRELOAD=/home/root/librm2fb_server.so.1.0.1 /usr/bin/rm_shutdown
```

**Comment by matteodelabre** [comment] 2021-08-13 15:14
Can you try replacing `/usr/bin/rm_shutdown` with `/usr/bin/xochitl` in the script?

**Comment by juanfcocontreras** [comment] 2021-08-13 15:20
> Can you try replacing `/usr/bin/rm_shutdown` with `/usr/bin/xochitl` in the script?

Sure, and it seems to be working great! Thanks a lot!

Just one more question. The script contains several calls to rm_shutdown, including checks whether the process is active in order to kill it. I have changed absolutely everything and it seems to work, but if you understand the script better, could you confirm that it is correct?

Thanks in advance.

**Comment by juanfcocontreras** [comment] 2021-08-13 15:23
I just saw that @Eeems eems is making a pull request that fixes these problems. Thank you very much!

Just commenting on the same question I just asked to @matteodelabre , there are more references to remarkable-shutdown (rm-shutdown) in that script. They should all be changed, right?

**Comment by Eeems** [comment] 2021-08-13 15:24
> 
> 
> I just saw that @Eeems eems is making a pull request that fixes these problems. Thank you very much!
> 
> Just commenting on the same question I just asked to @matteodelabre , there are more references to remarkable-shutdown (rm-shutdown) in that script. They should all be changed, right?

Correct, I'm writing the changes now.

**Comment by matteodelabre** [comment] 2021-08-13 15:25
> Just one more question. The script contains several calls to rm_shutdown, including checks whether the process is active in order to kill it. I have changed absolutely everything and it seems to work, but if you understand the script better, could you confirm that it is correct?

You should replace references to `/usr/bin/remarkable-shutdown` with `/usr/bin/xochitl` and `remarkable-shutdown` with `rm2fb-server` (using `xochitl` may work, but will probably also kill the real Xochitl).

**Comment by Eeems** [comment] 2021-08-13 15:27
> (using `xochitl` may work, but will probably also kill the real Xochitl).

You'd be correct, if you don't have `$NO_XO` set, it will kill the real xochitl instance. I'm working on handling that.

**Comment by matteodelabre** [comment] 2021-08-13 15:29
Thanks for working on the PR! I’m closing this since it’s not directly caused by rm2fb.

**Comment by Eeems** [comment] 2021-08-13 15:29
@juanfcocontreras the PR is ready I think? Would you be willing to test?

**Closed by matteodelabre** 2021-08-13 15:29 UTC

**Comment by juanfcocontreras** [comment] 2021-08-13 15:33
Sure, I leave my comments in the PR. Thanks to @matteodelabre

**Comment by matteodelabre** [comment] 2021-08-13 15:41
Happy to help!
