### ISSUE TITLE
White screen after boot - RM2 2.8.0.98

### ISSUE THREAD

**Issue by AAS97** [ddvk/remarkable2-framebuffer#67] opened 2021-07-30 16:32 UTC
Just tried to install rm2fb through _toltec_ before installing other apps and a launcher but I got a white screen just after install. White screen also after the boot screen.

I managed to get the UI back by SSHing back into the Rm2 and removing rm2fb.

Is 2.8.0.98 suported yet ? What did I do wrong ?

Last okpk prompt was : 
<img width="719" alt="Capture d’écran 2021-07-30 à 17 28 03" src="https://user-images.githubusercontent.com/28478916/127683691-bf080739-da11-4dd8-ba99-ab2c8fb2a3c7.png">

**Comment by Eeems** [comment] 2021-07-30 16:36
See the warning on https://toltec-dev.org You'll need to switch to the testing branch.
This looks like a duplicate of #63

**Comment by matteodelabre** [comment] 2021-08-23 09:22
Closing this. @AAS97 please feel free to re-open if you’re still having this issue. Also take a look at #63 as Eeems suggested.

**Closed by matteodelabre** 2021-08-23 09:22 UTC
