### ISSUE TITLE
rm2fb is not working on 2.6 (rm2)

### ISSUE THREAD

**Issue by erolx** [ddvk/remarkable2-framebuffer#57] opened 2021-03-23 20:48 UTC
rm2fb is not working on 2.6 (rm2). blank screen

**Comment by Eeems** [comment] 2021-03-23 20:49
Duplicate of #18 
Solved by #55

**Comment by musnit** [comment] 2021-03-30 00:26
@Eeems any way to apply the fix after install - just have a blank screen and can't ssh :S

**Closed** 2021-06-20 14:59 UTC
