### ISSUE TITLE
Stuck on Starting Screen - Toltec and RM2FB Install Issues

### ISSUE THREAD

**Issue by rmuser2** [ddvk/remarkable2-framebuffer#70] opened 2021-08-18 19:57 UTC
Hi all,

I had a go with Toltec and then I installed "opkg install rm2fb-client"
Then I installed draft but that didn't work. 

I have uninstalled everying using "toltecctl uninstall" but....

- My RM2 is stuck on the starting screen.
- I can still SSH into it and when I type "xochitl" it the software works fine, but it says "Codex is still running" in a banner on the bottom of the screen.
- On a restart, it gets stuck on starting
- On factory reset, it gets stuck on starting but when I ssh and type "xochitl", it starts back up and works fine (and I took note of the new SSH password!). This seems positive!

My laptop battery is dying, but that is all the info I have now. 

Any ideas? 

Many thanks!

**Comment by Eeems** [comment] 2021-08-18 20:32
What version of the OS are you running?

What information do you get when you run `systemctl status xochitl`? Likely you forgot to re-enable it after removing draft, and for some reason `toltecctl uninstall` didn't make sure it was re-enabled.

> I had a go with Toltec and then I installed "opkg install rm2fb-client"
> Then I installed draft but that didn't work.

That's only one half of the equation, you'd still need the rm2fb server, so `opkg install display`. That said, it's a dependency of draft and should have already been installed and running. I'm guessing you might be running OS 2.9 which is still making it's way to toltec stable.

>     * On factory reset, it gets stuck on starting but when I ssh and type "xochitl", it starts back up and works fine (and I took note of the new SSH password!). This seems positive!

A factory reset doesn't actually factory reset. It only resets xochitl configuration and removes data from the expected locations. It can soft-brick your device if you have third party applications installed.

**Comment by rmuser2** [comment] 2021-08-18 20:38
Thanks for the time, Nathaniel.

It is the latest 2.9 build, it was only updated a few hours before I started messing around with it.

systemctl status xochitl gives the below

> [0;1;31m●[[0m xochitl.service - reMarkable main application
     Loaded: loaded (/lib/systemd/system/xochitl.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/xochitl.service.d
             └─toltec-wrapper.conf
     Active: [[0;1;31mfailed[[0m (Result: exit-code) since Wed 2021-08-18 20:18:56 UTC; 16min ago
    Process: 235 ExecStart=/opt/bin/xochitl --system [[0;1;31m(code=exited, status=203/EXEC)[[0m
   Main PID: 235 (code=exited, status=203/EXEC)

>Aug 18 20:18:56 reMarkable systemd[1]: xochitl.service: Scheduled restart job, restart counter is at 4.
Aug 18 20:18:56 reMarkable systemd[1]: Stopped reMarkable main application.
Aug 18 20:18:56 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mxochitl.service: Start request repeated too quickly.[[0m
Aug 18 20:18:56 reMarkable systemd[1]: [[0;1;38;5;185m[[0;1;39m[[0;1;38;5;185mxochitl.service: Failed with result 'exit-code'.[[0m
Aug 18 20:18:56 reMarkable systemd[1]: [[0;1;31m[[0;1;39m[[0;1;31mFailed to start reMarkable main application.[[0m
Aug 18 20:18:56 reMarkable systemd[1]: xochitl.service: Triggering OnFailure= dependencies.

**Comment by rmuser2** [comment] 2021-08-18 20:41
`A factory reset doesn't actually factory reset. It only resets xochitl configuration and removes data from the expected locations. It can soft-brick your device if you have third party applications installed.`

The behaviour of the device didn't change after the factory reset. I was careful to get the new password, so I won't do it again. The reset did not fix the device getting stuck on "remarkable is starting". SSHing and typing xochitl was the only way I could get it running.

**Comment by Eeems** [comment] 2021-08-18 20:42
So it's failing to start the systemd service. By the looks of it, the uninstall missed the toltec-wrapper.conf. Could you open an issue on toltec about that. You can manually resolve it by running the following:
`rm -r /etc/systemd/system/xochitl.service.d`

**Comment by rmuser2** [comment] 2021-08-18 20:48
Oh wow, thank you for that. I got a warning (below). I ran the command it suggested and now it is booting again. Thanks for that, I will head to toltec and open the issue.

Warning: The unit file, source configuration file or drop-ins of xochitl.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by Eeems** [comment] 2021-08-18 20:50
I always forget about that whoops.

**Comment by matteodelabre** [comment] 2021-08-23 09:16
Closing this issue since this was caused by Toltec and not rm2fb.

**Closed by matteodelabre** 2021-08-23 09:16 UTC

**Comment by qubist** [comment] 2022-04-07 14:56
For anyone googling, I had an issue when running Oxide that prevented me from opening xochitl from the launcher. "Codex is still running" would flash and then it would go back to the launcher. I fixed it by rebooting and then running `systemctl daemon-reload`
